spring:
  cloud:
    stream:
      bindings:
        test:
          error-handler-definition: myErrorHandler
      kafka:
        bindings:
          test:
            producer:
              sync: true
        binder:
          brokers: localhost:9092
          configuration:
              retries: 3


